name: Container image publication
on:
  push:
    branches:
      - main
      - feat/js/image-publication
    tags:
      - v*
jobs:
  flake-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v16
        with:
          name: jisantuc
          authToken: '${{ secrets.CACHIX_TOKEN }}'

      - name: Log in to registry
        run: docker login ghcr.io -u jisantuc -p $CR_PAT
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - run: nix build .#containerImage.x86_64-linux
        env:
          ENV: ci

      - name: Load container image
        run: docker load < ./result

      - name: Push to registry
        run: docker push ghcr.io/jisantuc/schedule-2d-sat-sim:latest
