name: Container image publication
on:
  push:
    branches:
      - main
      - feat/js/image-publication
    tags:
      - v*
jobs:
  flake-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: jisantuc
          authToken: '${{ secrets.CACHIX_TOKEN }}'
      - run: nix build .#containerImage.x86_64-linux | podman load
        env:
          ENV: ci
      - name: Push to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: jisantuc/schedule-2d-sat-sim
          tag: latest
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
