name: CI
on:
  push:
    branches:
      main
  pull_request:
jobs:
  flake-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    services:
      redis:
        image: redis:7
        ports: 
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config:
            experimental-features=nix-command flakes
            trusted-public-keys=hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters=https://cache.iog.io
      - uses: cachix/cachix-action@v15
        with:
          name: jisantuc
          authToken: '${{ secrets.CACHIX_TOKEN }}'
      - run: nix develop .#ci --command ./scripts/test
        env:
          ENV: ci
      - run: nix build
      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@v4
        with:
          target: cabal:schedule-2d-sat-sim-test
          excludes: |
            SatSim.Algo.GreedySpec,
            SatSim.CacheSpec,
            SatSim.Gen.ProducerSpec
            SatSim.SchedulableSpec,
            SatSim.TargetVectorSpec
            SatSim.Consumer.AMQPSpec
      - name: Send coverage report
        uses: codecov/codecov-action@v5
