name: CI
on:
  push:
    branches:
      main
  pull_request:
jobs:
  flake-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    services:
      redis:
        image: redis:7
        ports: 
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v29
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters = https://cache.iog.io
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix develop .#ci --command ./scripts/test
        env:
          ENV: ci
      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@v4
        with:
          target: cabal:schedule-2d-sat-sim-test
          excludes: |
            SatSim.Algo.GreedySpec,
            SatSim.CacheSpec,
            SatSim.Gen.ProducerSpec
            SatSim.SchedulableSpec,
            SatSim.TargetVectorSpec
            SatSim.Consumer.AMQPSpec
      - name: Send coverage report
        uses: codecov/codecov-action@v5
