name: CI
on:
  push:
    branches:
      main
  pull_request:
jobs:
  flake-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    services:
      redis:
        image: redis:7
        ports: 
          - 6379:6379
      rabbitMQ:
        image: rabbitmq:4-alpine
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: jisantuc
          authToken: '${{ secrets.CACHIX_TOKEN }}'
      - run: nix develop .#ci --command ./scripts/test
        env:
          ENV: ci
      - run: nix build
      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@v4
        if: ${{ always() }}
        with:
          target: cabal:schedule-2d-sat-sim-test
          excludes: |
            SatSim.Algo.GreedySpec,
            SatSim.CacheSpec,
            SatSim.Core.ConsumerSpec,
            SatSim.Core.ScheduleRepositorySpec,
            SatSim.Gen.ProducerSpec,
            SatSim.SchedulableSpec,
            SatSim.TargetVectorSpec,
            SatSim.TestLib
      - name: Send coverage report
        uses: codecov/codecov-action@v5
        if: ${{ always() }}
